# Generated by Django 5.2.4 on 2025-07-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
