# Generated by Django 5.2.4 on 2025-07-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workspace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
