# Generated by Django 5.2.4 on 2025-07-11 17:37
from django.db import migrations

# Lista de roles que queremos crear por defecto
DEFAULT_ROLES = [
    {"name": "Dueño", "description": "Tiene todos los permisos sobre el workspace."},
    {"name": "Admin", "description": "Puede gestionar miembros y proyectos."},
    {"name": "Miembro", "description": "Puede gestionar tareas y comentar."},
    {"name": "Invitado", "description": "Solo tiene permisos de lectura."},
]

def create_roles(apps, schema_editor):
    """
    Esta función se ejecuta cuando aplicamos la migración.
    Crea los roles por defecto en la base de datos.
    """
    # Obtenemos el modelo 'Role' de nuestra app 'core'
    Role = apps.get_model('core', 'Role')
    
    for role_data in DEFAULT_ROLES:
        # Usamos get_or_create para no crear duplicados si la migración se corre de nuevo
        Role.objects.get_or_create(name=role_data['name'], defaults=role_data)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_role_alter_membership_role'),
    ]

    operations = [
        # Le decimos a Django que ejecute nuestra función create_roles
        migrations.RunPython(create_roles),
    ]
