# Generated by Django 5.2.4 on 2025-07-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_create_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin_role',
            field=models.BooleanField(default=False, help_text='Marcar si este rol tiene permisos de administrador.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
