# Generated by Django 5.2.4 on 2025-07-30 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customfield_fieldoption_customfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_points',
            field=models.PositiveSmallIntegerField(default=1, help_text='Puntos de esfuerzo estimados para esta tarea (ej: 1, 2, 3, 5, 8)'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='core.task'),
        ),
    ]
