# Generated by Django 5.2.4 on 2025-07-30 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_task_effort_points_alter_customfieldvalue_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto total estimado para el proyecto.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del proyecto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('ON_HOLD', 'En Pausa'), ('ARCHIVED', 'Archivado')], default='ACTIVE', max_length=10),
        ),
    ]
